version: "3.1"

services:
  db:
    image: mysql
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - ./db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    networks:
      default:
        aliases:
          - db
  web:
    build: backend
    ports:
      - "8080:8080"
    depends_on:
        db:
            condition: service_started
    environment:
      SECRETKEY: ${SECRETKEY}
    networks:
      default:
        aliases:
          - web
  frontend:
    build: frontend
    ports:
      - "80:5173"
    depends_on:
        web:
            condition: service_started
    networks:
        default:
            aliases:
            - frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules

networks:
  default:

volumes:
    db:
