version: "3.8"

services:
  db:
    image: mysql
    ports:
      - "3306:3306"
    volumes:
      - ./db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    networks:
      default:
        aliases:
          - db
  backend:
    image: backend:latest
    ports:
      - "8080:8080"
    depends_on:
        db:
            condition: service_started
    environment:
        SECRETKEY: ${SECRETKEY}
        SEED: ${SEED}
    networks:
        default:
            aliases:
            - web
  frontend:
    build: frontend
    ports:
      - "5173:5173"
    depends_on:
        backend:
            condition: service_started
    networks:
        default:
            aliases:
            - frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules

networks:
  default:

volumes:
    db:
